<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>se.deversity.codekarta.it</groupId>
    <artifactId>fail-on-empty</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>se.deversity.codekarta</groupId>
                <artifactId>code-karta-maven-plugin</artifactId>
                <version>@project.version@</version>
                <executions>
                    <execution>
                        <goals><goal>generate</goal></goals>
                    </execution>
                </executions>
                <configuration>
                    <failOnEmpty>true</failOnEmpty>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
